spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farm
    username: postgres
    password: postgre1488rp
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      url: jdbc:redis://localhost:6379/0

server:
  port: 8081
