spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farm
    username: postgres
    password: postgre1488rp
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      url: jdbc:redis://localhost:6379/0

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.mail.ru
    port: 465
    username: ilya-shulenin@mail.ru
    password: p9fkFzpAx2zLtXvRaecr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtps

server:
  port: 8082

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
